CONFIG_NAME: 'movie'
dataset_name: 'movie'
data_dir: '../data/movie'

imsize: 256
z_dim: 100
cond_dim: 512
manual_seed: 100
cuda: True

bert_model_name : 'bert-base-chinese'
num_labels : 3

clip4evl: {'src':"clip", 'type':'ViT-B/32'}
clip4trn: {'src':"clip", 'type':'ViT-B/32'} 
clip4text: {'src':"clip", 'type':'ViT-B/32'} 

stamp: 'normal'
state_epoch: 0
max_epoch: 3 ###changed
batch_size: 16
gpu_id: 0
nf: 64
ch_size: 3
text_feature_size: 64  ##4.12

hidden_size: 64
output_size: 4
mixed_precision: False
num_classes: 4   #4.17

scaler_min: 64
growth_interval: 2000
lr_g: 0.000001 #0.0001
lr_d: 0.000004 #0.0004
lr_c: 0.0001  #0419
sim_w: 4.0

gen_interval: 1 #1   ##changed 5
test_interval: 1 #5   ##changed 20
save_interval: 1  ##changed 20

sample_times: 12
npz_path: '../data/movie/npz/fid_stat.npz'
log_dir: 'new'